-  name: variable in ansible
   hosts: mongodb
   vars:
      COURSE: devops
      TRAINER: vinay
      DURATION: 50hrs
   tasks:
   - name: print hello world
     ansible.builtin.debug:
       msg: "hello, i a learning devops"
   - name: print in variables
     ansible.builtin.debug:
       msg:     
         